### PR TITLE
fix: footer

### PR DESCRIPTION
**Pull request by Tnixc**
https://user-images.githubusercontent.com/85466117/216559933-f93a1085-2c47-4e23-9598-aeacfd0c43a5.mov

Fixes this issue

### CODE REVIEW

**Comment by andreasgrafen** [comment]
May I ask which version of the Userstyle you currently have installed? Because the issue you're pointing out in your screencap doesn't seem to appear for me. o:

GitHub Footer Screenshot

**Comment by Tnixc** [comment]
Just updated to 1.11, issue still occurs.

**Comment by andreasgrafen** [comment]
That's really odd.. could you do a quick sanity check and make sure no other stylus themes are applied for whatever reason? I'd really love to figure out how to reproduce this issue. o:

**Comment by rubyowo** [comment]
can repro
image

**Comment by andreasgrafen** [comment]
I haven't found a way to reproduce this – even with the LESS rework I didn't run into this issue. Merging it doesn't hurt, so.. yeah. :D

**Comment by m-wynn** [comment]
I believe this PR is missing a close curly-bracket on `nav.col-12`

**Pull request merged**
